name: bayes_spec-dev
channels:
  - conda-forge
  - nvidia
  - defaults
dependencies:
  - ipython
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - ipywidgets
  - versioneer
  - black
  - flake8
  - pytest
  - pytest-cov
  - pymc>=5
  - pytensor
  - nutpie
  - numba
  - arviz
  - matplotlib
  - scipy
  - scikit-learn
  - graphviz
  - nvidia::cuda-toolkit
  - jaxlib=*=*cuda*
  - jax==0.4.28
  - blackjax
  - numpyro
