name: bayes_spec-dev
channels:
  - conda-forge
  - defaults
dependencies:
  - ipython
  - jupyter_contrib_nbextensions
  - jupyter_nbextensions_configurator
  - ipywidgets
  - versioneer
  - numpy
  - pymc>=5
  - pytensor
  - nutpie
  - numba
  - arviz
  - matplotlib
  - scipy
  - scikit-learn
  - graphviz
  - jax==0.4.28
  - blackjax
  - numpyro
  - black
  - flake8
